// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfktpmsvcoepoqyzezhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impma3RwbXN2Y29lcG9xeXplemhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTMwNjgsImV4cCI6MjA3Mzc2OTA2OH0.O45d0cKDT-qFwdSFpI393t8Rq-yOpDsUbPrxlssL7_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});